name: CI
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
jobs:
 conviso-ast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/convisocli:unstable
     env:
       FLOW_API_KEY: ${{secrets.CONVISO_API_KEY}}
       #CONVISO_ASSET_NAME: "github-vwa-fverga-cli"
       CONVISO_COMPANY_ID: 600
   steps:
   - uses: actions/checkout@v4

   - name: Run AST
     run: conviso ast run --vulnerability-auto-close
